services:
  web:
    build: .
    ports:
      - "127.0.0.1:8092:80"
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      # test: ["CMD", "false"]
      interval: 5s
      timeout: 3s
      retries: 3

  db:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: always

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime_kuma_data:/app/data
    depends_on:
      - web

volumes:
  redis_data:
  uptime_kuma_data:
